# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ deploy-test ]
  pull_request:
    branches: [ deploy-test ]

jobs:
  build:
    env:
      working-directory: backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # JDK11로 gradle 빌드
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Insert data source information into application.yml
        run: |
          sed -i "s|\${MYSQL_HOST}|$MYSQL_HOST|g" ./src/main/resources/application-deploy.yml
          sed -i "s|\${MYSQL_USERNAME}|$MYSQL_USERNAME|g" ./src/main/resources/application-deploy.yml
          sed -i "s|\${MYSQL_PASSWORD}|$MYSQL_PASSWORD|g" ./src/main/resources/application-deploy.yml
          sed -i "s|\${CLIENT_ID}|$CLIENT_ID|g" ./src/main/resources/application-deploy.yml
          sed -i "s|\${CLIENT_SECRET}|$CLIENT_SECRET|g" ./src/main/resources/application-deploy.yml
          sed -i "s|\${JWT_ISSUER}|$JWT_ISSUER|g" ./src/main/resources/application-deploy.yml
          sed -i "s|\${JWT_SECRET}|$JWT_SECRET|g" ./src/main/resources/application-deploy.yml
        working-directory: ${{env.working-directory}}
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{env.working-directory}}
      - name: Build with Gradle
        run: ./gradlew bootJar
        working-directory: ${{env.working-directory}}

      # 도커 빌드(도커 이미지 생성)
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/codesquad-issue-tracker:1.0 .
          docker push ${{ secrets.DOCKER_USERNAME }}/codesquad-issue-tracker:1.0
          docker rmi ${{ secrets.DOCKER_USERNAME }}/codesquad-issue-tracker:1.0
        working-directory: ${{env.working-directory}}

      # 도커 이미지 배포 및 실행(EC2 ubuntu20.04로 배포)
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_DNS }} #(생성한 인스턴스의 DNS주소)
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }} #(인스턴스를 생성할 때 다운받은 pem키안에 값을 모두 복사해서 붙여넣기)
          envs: GITHUB_SHA
          script: |
            sudo docker ps -a -q --filter "name=codesquad-issue-tracker" | grep -q . && docker stop codesquad-issue-tracker && docker rm codesquad-issue-tracker | true
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/codesquad-issue-tracker:1.0
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/codesquad-issue-tracker:1.0
            sudo docker run -d -p 80:8080 --name codesquad-issue-tracker ${{ secrets.DOCKER_USERNAME }}/codesquad-issue-tracker:1.0
            sudo docker rmi -f $(docker images -f "dangling=true" -q) || true
